### PR TITLE
Docs improvements

### PR DESCRIPTION
**Pull request by petrparolek**
Polished docs
- use 4 spaces in CSS, in JS, in HTML and in Latte
- use tab in NEON and in PHP
- neon highlighting syntax
- normalized filename of Readmes
- typos

### CODE REVIEW

**Comment by paveljanda** [comment]
Could you please resolve conflicts? Thanks

**Comment by petrparolek** [comment]
I don't see any merge conflicts

**Comment by petrparolek** [comment]
obrazek

**Comment by petrparolek** [comment]
obrazek

**Comment by paveljanda** [comment]
Screenshot 2021-03-11 at 10 41 45

Interesting.

**Comment by petrparolek** [comment]
try it now.

**Comment by petrparolek** [comment]
oh no, I closed it and I can'rt reopen. Is it merge?

**Comment by petrparolek** [comment]
I see, it is buggy GUI of GitHub, It should be shown merged not closed!

**Pull request closed without merging**
